### PR TITLE
Improve formatter on Payment.fns

### PR DESCRIPTION
**Pull request by james-song**
Fixed, #35

### CODE REVIEW

**Comment by jessepollak** [comment]
This looks really great! A few things:

1) Can you remove the `yarn.lock` file?
2) It looks like the new formatting functions aren't actually used in the publicly exposed formatters. Can you hook those up?

Thank you so much!

**Comment by jessepollak** [comment]
This looks really great! A few things:

1) Can you remove the `yarn.lock` file?
2) It looks like the new formatting functions aren't actually used in the publicly exposed formatters. Can you hook those up?

Thank you so much!

**Comment by james-song** [comment]
1. sure
2. i think, webpack config is something wrong, converted JS file by coffee script compile at `lib/index.js` module is working.

```
rock@rock-macpro:~/work/payment (master)$node
> require('./lib/index.js')
{ [Function: Payment]
  fns:
   { cardExpiryVal: [Function: cardExpiryVal],
     validateCardNumber: [Function: validateCardNumber],
     validateCardExpiry: [Function: validateCardExpiry],
     validateCardCVC: [Function: validateCardCVC],
     cardType: [Function: cardType],
     formatCardNumber: [Function: formatCardNumber],
     formatCardCVC: [Function: formatCardCVC],
     formatCardExpiry: [Function: formatCardExpiry] },
  restrictNumeric: [Function],
  cardExpiryVal: [Function],
  formatCardCVC: [Function],
  formatCardExpiry: [Function],
  formatCardExpiryMultiple: [Function],
  formatCardNumber: [Function],
  getCardArray: [Function],
  setCardArray: [Function],
  addToCardArray: [Function],
  removeFromCardArray: [Function] }
>
```

Did you check by this module ? or `dist/payment.js` module ?

**Comment by jessepollak** [comment]
I'm just looking at your PR and the fact that your new `formatCardExpiry` function is not used [here](https://github.com/jessepollak/payment/pull/61/files#diff-2fbc5085a7bbe6fb696a1a3b75a6f420L469). Does that make sense?

**Comment by james-song** [comment]
Okey, i understand your review, 
Sorry about i was misunderstand your comment.

give a some time. i'm coffee script beginner.

**Comment by james-song** [comment]
Finally, apply review feedback!
:) !

**Pull request closed without merging**
