### PR TITLE
Updated Diners Club Format

### PR DESCRIPTION
**Pull request by joshluongo**
Changed the diners club format to: XXXX XXXXXX XXXX.

### CODE REVIEW

**Comment by jessepollak** [comment]
Hi! Where do you see this listed as the format? Thanks!

**Comment by joshluongo** [comment]
Stripe's jquery.payment has it [jquery.payment.coffee line 109](https://github.com/stripe/jquery.payment/blob/master/src/jquery.payment.coffee#L109).

Also if you checkout [this sample card](http://www.hdfcbank.com/assets/images/diners-premium.png) it has that format.

**Comment by jessepollak** [comment]
Thanks — I'll make this update as soon as possible!

**Comment by jessepollak** [comment]
Thanks!

**Pull request merged**
