### PR TITLE
Remove e.prevendDefault() for React.js compatibility

### PR DESCRIPTION
**Pull request by RostislavMitu**
Solution for this issue: https://github.com/jessepollak/payment/issues/66

### CODE REVIEW

**Comment by a-wart** [comment]
@jessepollak

**Comment by a-wart** [comment]
@jessepollak ping:)

**Comment by a-wart** [comment]
@RostislavMitu there is another issue with this fix: if you lose focus from card number field once, you can't edit or delete it with backspace/delete anymore.

**Comment by jessepollak** [comment]
Thanks for your fix!

**Comment by jessepollak** [comment]
Hi! I pre-emptively merged this — it breaks tests. Can you fix it so tests don't break (or fix the tests so they pass) and then re-submit? Thanks!

**Pull request merged**
