### PR TITLE
build the library

### PR DESCRIPTION
**Pull request by bchelli**
After the previous modification of the library in coffeescript we were missing the build part
=> the library remained the same

### CODE REVIEW

**Comment by jessepollak** [comment]
Thanks!

**Comment by bchelli** [comment]
Hey @jessepollak,

Thank you for this super nice lib.
Also, could you push 0.0.9 to the NPM repository too?

Thanks,

**Comment by jessepollak** [comment]
Whoops - sorry about that, published!

**Comment by bchelli** [comment]
Thanks

**Pull request merged**
